package com.kang.ebook;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;

/*
 * This is for quick extract book from studing bible./
 *  
 * In this site, chapter links start with a common prefix then appended with the chapter sequence
 * then appended with a common suffix.
 * 
 * The links array can be generated by viewing source of the first page, the 11th page .....
 * 
 * Finally write the pages in sequence to a file of html. 
 * 
 * 
 */
public class StudyBibleGrabber {
	//this is the html file going to be generated.
	private String bookFileName = "1.html";
	private String[] links = {
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET00.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET01.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET02.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET03.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET04.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET05.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET06.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET07.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET08.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET09.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET10.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET11.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET12.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET13.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET14.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET15.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET16.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET17.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET18.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET19.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET20.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET21.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET22.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET23.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET24.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET25.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET26.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET27.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET28.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET29.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET30.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET31.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET32.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET33.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET34.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET35.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET36.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET37.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET38.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET39.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET40.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET41.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET42.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET43.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET44.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET45.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET46.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET47.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET48.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET49.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET50.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET51.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET52.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET53.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET54.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET55.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET56.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET57.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET58.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET59.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET60.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET61.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET62.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET63.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET64.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET65.htm",
			"http://www.edzx.com/chajing/Old%20Testament/23Isa/23ET66.htm"
	};
	
	
	private String prefix = "<TD CLASS=ART>";
	private String suffix = "<DIV class=FL>";
	
	private int chapterIntervals = 1000;
	
	public static void main(String[] args) {
		StudyBibleGrabber ebook = new StudyBibleGrabber();
		System.out.println("------Done-----");
	}

	public StudyBibleGrabber() {
		
		
//		finalResult.append("<html><body>");
		for (int i=0; i< links.length; i++) {
			String link = (String) links[i];
			StringBuffer finalResult = new StringBuffer();

			try {
				String pageContent = getPageDetails(link);
//				finalResult.append("<p>");
				finalResult.append(pageContent);
//				finalResult.append("<p>");

				String bf = link.substring(link.lastIndexOf("/")+ 1);
				writeFile(finalResult.toString(), bf);
				
				Thread.sleep(chapterIntervals); // sleep for  mil-second before retrieving the page
									
				
			} catch (Exception e) {
				e.printStackTrace();
			}
			System.out.println("Done with " + link);
		}

//		finalResult.append("</body></html>");

	}

	

	/*
	 * Has the http link of a page, get the content as a formatted html
	 * string
	 */
	private String getPageDetails(String link) {
		String pageFullContent = getWebPageInFullHttpResponse(link);
		
//		String pageContent = "";
//		
//		try {
//			pageContent = getWebPart(pageFullContent, prefix, suffix);
//		} catch(Exception e){
//			
//		}
		return pageFullContent;
	}

	private void writeFile(String content, String filename) {
		try {
			PrintWriter out = new PrintWriter(new FileOutputStream(filename));

			out.print(content);
			out.flush();
			out.close();
			out = null;
		} catch (Exception e) {
		}
	}

	private String getWebPageInFullHttpResponse(String sitelink) {
		StringBuffer webPageBuffer = new StringBuffer();

		try {
			URL url = new URL(sitelink);

			URLConnection uc = url.openConnection();

			BufferedReader in = new BufferedReader(new InputStreamReader(uc
					.getInputStream()));
			String inputLine;

			while ((inputLine = in.readLine()) != null) {
//				webPageBuffer.append("<BR>" + inputLine);
				webPageBuffer.append(inputLine);
			}
			in.close();
		} catch (Exception e) {
			System.out.println("Error with link: " + sitelink);
		}

		return webPageBuffer.toString();
	}

	private String getWebPart(String input, String prefix, String suffix) {
		String part;

		int index = 0;

		index = input.indexOf(prefix) ;

		input = input.substring(index);

		index = input.indexOf(suffix);

		part = input.substring(0, index);

		return part;
	}

}
