package com.kang.ebook;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;

/*
 * This is for quick extract book from 天涯煮酒论史 
 *  
 * In this site, chapter links start with a common prefix then appended with the chapter sequence
 * then appended with a common suffix.
 * 
 * The links array can be generated by viewing source of the first page, the 11th page .....
 * 
 * Finally write the pages in sequence to a file of html. 
 * 
 * 
 */
public class TianYaEbook {
	//this is the html file going to be generated.
	private String bookFileName = "新概念水浒.html";
	private String[] links = {
			"http://www.tianya.cn/publicforum/content/no05/1/120855.shtml",
			"http://www.tianya.cn/publicforum/content/no05/1/121112.shtml",
			"http://www.tianya.cn/publicforum/content/no05/1/121531.shtml",
	};
	
	
	private String prefix = "<div class=\"body\" >";
	private String suffix = "</BODY>";
	
	private int chapterIntervals = 1000;
	
	public static void main(String[] args) {
		TianYaEbook ebook = new TianYaEbook();
		System.out.println("------Done-----");
	}

	public TianYaEbook() {
		
		StringBuffer finalResult = new StringBuffer();

		finalResult.append("<html><body>");
		for (int i=0; i< links.length; i++) {
			String link = (String) links[i];

			try {
				String pageContent = getPageDetails(link);
				finalResult.append("<p>");
				finalResult.append(pageContent);
				finalResult.append("<p>");

				Thread.sleep(chapterIntervals); // sleep for  mil-second before retrieving the page
									

			} catch (Exception e) {
				e.printStackTrace();
			}
			System.out.println("Done with " + link);
		}

		finalResult.append("</body></html>");

		writeFile(finalResult.toString(), bookFileName);
	}

	

	/*
	 * Has the http link of a page, get the content as a formatted html
	 * string
	 */
	private String getPageDetails(String link) {
		String pageFullContent = getWebPageInFullHttpResponse(link);
		
		String pageContent = "";
		
		try {
			pageContent = getWebPart(pageFullContent, prefix, suffix);
		} catch(Exception e){
			
		}
		return pageContent;
	}

	private void writeFile(String content, String filename) {
		try {
			PrintWriter out = new PrintWriter(new FileOutputStream(filename));

			out.print(content);
			out.flush();
			out.close();
			out = null;
		} catch (Exception e) {
		}
	}

	private String getWebPageInFullHttpResponse(String sitelink) {
		StringBuffer webPageBuffer = new StringBuffer();

		try {
			URL url = new URL(sitelink);

			URLConnection uc = url.openConnection();

			BufferedReader in = new BufferedReader(new InputStreamReader(uc
					.getInputStream()));
			String inputLine;

			while ((inputLine = in.readLine()) != null) {
				webPageBuffer.append("<BR>" + inputLine);
			}
			in.close();
		} catch (Exception e) {
			System.out.println("Error with link: " + sitelink);
		}

		return webPageBuffer.toString();
	}

	private String getWebPart(String input, String prefix, String suffix) {
		String part;

		int index = 0;

		index = input.indexOf(prefix) ;

		input = input.substring(index);

		index = input.indexOf(suffix);

		part = input.substring(0, index);

		return part;
	}

}
