package com.kang.ebook;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;

/*
 * This is for quick extract book from ÌìÑÄÖó¾ÆÂÛÊ· 
 *  
 * In this site, chapter links start with a common prefix then appended with the chapter sequence
 * then appended with a common suffix.
 * 
 * The links array can be generated by viewing source of the first page, the 11th page .....
 * 
 * Finally write the pages in sequence to a file of html. 
 * 
 * 
 */
public class YiDuEbook {
	//this is the html file going to be generated.
	private String bookFileName = "1.html";
	private String[] links = {
			"http://www.yi-see.com/read_117893_12692.html",
			"http://www.yi-see.com/read_117894_12692.html",
			"http://www.yi-see.com/read_117895_12692.html",
			"http://www.yi-see.com/read_117896_12692.html",
			"http://www.yi-see.com/read_117897_12692.html",
			"http://www.yi-see.com/read_117898_12692.html",
			"http://www.yi-see.com/read_117899_12692.html",
			"http://www.yi-see.com/read_117900_12692.html",
			"http://www.yi-see.com/read_117901_12692.html",
			"http://www.yi-see.com/read_117902_12692.html",
			"http://www.yi-see.com/read_117903_12692.html",
			"http://www.yi-see.com/read_117904_12692.html",
			"http://www.yi-see.com/read_117905_12692.html",
			"http://www.yi-see.com/read_117906_12692.html",
			"http://www.yi-see.com/read_117907_12692.html",
			"http://www.yi-see.com/read_117908_12692.html",
			"http://www.yi-see.com/read_117909_12692.html",
			"http://www.yi-see.com/read_117910_12692.html",
			"http://www.yi-see.com/read_117911_12692.html",
			"http://www.yi-see.com/read_117912_12692.html",
			"http://www.yi-see.com/read_117913_12692.html",
			"http://www.yi-see.com/read_117914_12692.html",
			"http://www.yi-see.com/read_117915_12692.html",
			"http://www.yi-see.com/read_117916_12692.html",
			"http://www.yi-see.com/read_117917_12692.html",
			"http://www.yi-see.com/read_117918_12692.html",
			"http://www.yi-see.com/read_117919_12692.html",
			"http://www.yi-see.com/read_117920_12692.html",
			"http://www.yi-see.com/read_117921_12692.html",
			"http://www.yi-see.com/read_117922_12692.html",
			"http://www.yi-see.com/read_117923_12692.html",
			"http://www.yi-see.com/read_117924_12692.html",
			"http://www.yi-see.com/read_117925_12692.html",
			"http://www.yi-see.com/read_117926_12692.html",
			"http://www.yi-see.com/read_117927_12692.html",
			"http://www.yi-see.com/read_117928_12692.html",
			"http://www.yi-see.com/read_117929_12692.html",
			"http://www.yi-see.com/read_117930_12692.html",
			"http://www.yi-see.com/read_117931_12692.html",
			"http://www.yi-see.com/read_117932_12692.html",
			"http://www.yi-see.com/read_117933_12692.html",
			"http://www.yi-see.com/read_117934_12692.html",
			"http://www.yi-see.com/read_117935_12692.html",
			"http://www.yi-see.com/read_117936_12692.html",
			"http://www.yi-see.com/read_117937_12692.html",
			"http://www.yi-see.com/read_117938_12692.html",
			"http://www.yi-see.com/read_117939_12692.html",
			"http://www.yi-see.com/read_117940_12692.html",
			"http://www.yi-see.com/read_117941_12692.html",
			"http://www.yi-see.com/read_117942_12692.html",
			"http://www.yi-see.com/read_117943_12692.html",
			"http://www.yi-see.com/read_117944_12692.html",
			"http://www.yi-see.com/read_117945_12692.html",
			"http://www.yi-see.com/read_117946_12692.html",
			"http://www.yi-see.com/read_117947_12692.html",
			"http://www.yi-see.com/read_117948_12692.html",
			"http://www.yi-see.com/read_117949_12692.html",
			"http://www.yi-see.com/read_117950_12692.html",
			"http://www.yi-see.com/read_117951_12692.html",
			"http://www.yi-see.com/read_117952_12692.html",
			"http://www.yi-see.com/read_117953_12692.html",
			"http://www.yi-see.com/read_117954_12692.html",
			"http://www.yi-see.com/read_117955_12692.html",
			"http://www.yi-see.com/read_117956_12692.html",
			"http://www.yi-see.com/read_117957_12692.html",
			"http://www.yi-see.com/read_117958_12692.html",
			"http://www.yi-see.com/read_117959_12692.html",
			"http://www.yi-see.com/read_117960_12692.html",
			"http://www.yi-see.com/read_117961_12692.html"
	};
	
	
	private String prefix = "<TD CLASS=ART>";
	private String suffix = "<DIV class=FL>";
	
	private int chapterIntervals = 1000;
	
	public static void main(String[] args) {
		YiDuEbook ebook = new YiDuEbook();
		System.out.println("------Done-----");
	}

	public YiDuEbook() {
		
		StringBuffer finalResult = new StringBuffer();

		finalResult.append("<html><body>");
		for (int i=0; i< links.length; i++) {
			String link = (String) links[i];

			try {
				String pageContent = getPageDetails(link);
				finalResult.append("<p>");
				finalResult.append(pageContent);
				finalResult.append("<p>");

				Thread.sleep(chapterIntervals); // sleep for  mil-second before retrieving the page
									

			} catch (Exception e) {
				e.printStackTrace();
			}
			System.out.println("Done with " + link);
		}

		finalResult.append("</body></html>");

		writeFile(finalResult.toString(), bookFileName);
	}

	

	/*
	 * Has the http link of a page, get the content as a formatted html
	 * string
	 */
	private String getPageDetails(String link) {
		String pageFullContent = getWebPageInFullHttpResponse(link);
		
		String pageContent = "";
		
		try {
			pageContent = getWebPart(pageFullContent, prefix, suffix);
		} catch(Exception e){
			
		}
		return pageContent;
	}

	private void writeFile(String content, String filename) {
		try {
			PrintWriter out = new PrintWriter(new FileOutputStream(filename));

			out.print(content);
			out.flush();
			out.close();
			out = null;
		} catch (Exception e) {
		}
	}

	private String getWebPageInFullHttpResponse(String sitelink) {
		StringBuffer webPageBuffer = new StringBuffer();

		try {
			URL url = new URL(sitelink);

			URLConnection uc = url.openConnection();

			BufferedReader in = new BufferedReader(new InputStreamReader(uc
					.getInputStream()));
			String inputLine;

			while ((inputLine = in.readLine()) != null) {
//				webPageBuffer.append("<BR>" + inputLine);
				webPageBuffer.append(inputLine);
			}
			in.close();
		} catch (Exception e) {
			System.out.println("Error with link: " + sitelink);
		}

		return webPageBuffer.toString();
	}

	private String getWebPart(String input, String prefix, String suffix) {
		String part;

		int index = 0;

		index = input.indexOf(prefix) ;

		input = input.substring(index);

		index = input.indexOf(suffix);

		part = input.substring(0, index);

		return part;
	}

}
